In [2]:
#Answer 1:

#import numpy with alias name
import numpy as np

#create array using np.arange
arr = np.arange(2,50,3)

#print numpy array
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [7]:
# Answer 2:

import numpy as np

#two empty lists
list1 = []
list2 = []

#getting list1 elements from users
for i in range(5):
    l1 = int(input("\nEnter elements in list 1 :"))
    list1.append(l1)
print("\nElements in list 1:",list1)

#getting list 2 elememts from user
for i in range(5):
    l2 = int(input("\nEnter elements in list 2 :"))
    list2.append(l2)
print("\nElements in list 2 :",list2)
    
#conversion of list into numpy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

#concatenation of numpy arrays and printing
arr = np.concatenate((arr1,arr2))
print("After concatenation of arrays :",arr)

#sorting of numpy arrays
arrsort = np.sort(arr)
print("After sorting of arrays :",arrsort)


Enter elements in list 1 :20

Enter elements in list 1 :4

Enter elements in list 1 :8

Enter elements in list 1 :1

Enter elements in list 1 :9

Elements in list 1: [20, 4, 8, 1, 9]

Enter elements in list 2 :34

Enter elements in list 2 :9

Enter elements in list 2 :3

Enter elements in list 2 :7

Enter elements in list 2 :6

Elements in list 2 : [34, 9, 3, 7, 6]
After concatenation of arrays : [20  4  8  1  9 34  9  3  7  6]
After sorting of arrays : [ 1  3  4  6  7  8  9  9 20 34]


In [13]:
#Answer 3:

import numpy as np

#create a numpy array
arr = np.array([[1,2,3],[4,5,6],[7,8,90]])
print(arr)

#print dimensions of the numpy array using (arayname.ndim)
print("The dimension of the given array is :",arr.ndim)

#print size of numpy array using (arrayname.size)
print("The size of the given array is :",arr.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 90]]
The dimension of the given array is : 2
The size of the given array is : 9


In [15]:
#Answer 4:

import numpy as np

#conversion of 1d array to 2d array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np. reshape(arr, (2, 5))
print(arr_2d)

                                #conversion of arrays using np.newaxis


#np.newaxis is used to increase dimensions of existing array by one more dimension, when used once. 

#make it as row vector by inserting an axis along first dimension
arr_row = arr[np.newaxis,:]
print("array in row :",arr_row.shape)

#make it as column vector by inserting an axis along second dimension
arr_col = arr[:,np.newaxis]
print("array in column :",arr_col.shape)


                                 #conversion of arrays using expand_dims
    

# creating a 1d array
arr = np.arange(10)
print("\nShape of Array :",arr.shape)

# converting using newaxis in row wise
row_arr = np.expand_dims(arr, axis=0)
print("\nShape of 2d Array in row :",row_arr.shape)

# converting using newaxis in column wise
col_arr = np.expand_dims(arr, axis=1)
print("\nShape of 2d Array in column :",col_arr.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
array in row : (1, 10)
array in column : (10, 1)

Shape of Array : (10,)

Shape of 2d Array in row : (1, 10)

Shape of 2d Array in column : (10, 1)


In [17]:
#Answer 5:

import numpy as np

# creating a array with square values
arr_1 = np.square([1, 2, 3, 4, 5])
arr_2 = np.square([6, 7, 8, 9, 10])

# stacking and printing the value
print("\nHorizontal stack :", np.hstack((arr_1, arr_2)))
print("\nVertical stack :", np.vstack((arr_1, arr_2)))


Horizontal stack : [  1   4   9  16  25  36  49  64  81 100]

Vertical stack : [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


In [20]:
#Answer 6

#create numpy arrray
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)

# Get a tuple of unique values & their frequency in numpy array
uniqueValues, occurCount = np.unique(arr, return_counts=True)
print("Unique Values : " , uniqueValues)
print("Occurrence Count : ", occurCount)

Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
Occurrence Count :  [3 2 2 2 1 1 1 1]
